### ISSUE TITLE
Does not recognise Dash.app's directory structure

### ISSUE THREAD

**Issue by 00dani** [sunaku/dasht#20] opened 2017-03-22 00:59 UTC
I'm already using Dash.app and have various docsets installed, so I figured I'd point `dasht` at my existing docsets with `DASHT_DOCSETS_DIR`. Unfortunately:
```shellsession
$ export DASHT_DOCSETS_DIR=~/Library/Application\ Support/Dash/DocSets
$ dasht-docsets # nothing is output
$ export DASHT_DOCSETS_DIR=~/Library/Application\ Support/Dash/DocSets/Ruby_2
$ dasht-docsets
Ruby
```
In other words, Dash.app puts the actual `Something.docset` directories a layer further down, inside language-specific subdirectories of the general `DocSets` directory. `dasht` does not anticipate this extra layer and does not understand it, hence it finds no docsets.

Could `dasht` be taught to look for docsets recursively from the configured docsets dir, to make it compatible with the organisation Dash.app uses?

**Comment by sunaku** [comment] 2017-03-27 23:59
Thanks for your report. :+1:  This is a duplicate of issue #15, so please follow the discussion there. :loop:

**Closed by sunaku** 2017-03-27 23:59 UTC
